#include "screen.h"


void title(void)
{
    SetCursorPosition(0,0);
    printf("┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐");
    sleep(10);
    SetCursorPosition(0,1);
    printf("│     ______                                                    \x1b[32m______\x1b[0m                                   │  ");
    sleep(10);
    SetCursorPosition(0,2);
    printf("│     | ___ \\                                                  \x1b[32m| ___ \\\x1b[0m                                   │");
    sleep(10);
    SetCursorPosition(0,3);
    printf("│     | |_/ /  __ _  _ __    __ _  _ __    __ _                \x1b[32m| |_/ /  ___  ___   ___  _   _   ___\x1b[0m      │");
    sleep(10);
    SetCursorPosition(0,4);
    printf("│     | ___ \\ / _` || '_ \\  / _` || '_ \\  / _` |               \x1b[32m|    /  / _ \\/ __| / __|| | | | / _ \\\x1b[0m     │");
    sleep(10);
    SetCursorPosition(0,5);
    printf("│     | |_/ /| (_| || | | || (_| || | | || (_| |               \x1b[32m| |\\ \\ |  __/\\__ \\| (__ | |_| ||  __/\x1b[0m     │");
    sleep(10);
    SetCursorPosition(0,6);
    printf("│     \\____/  \\__,_||_| |_| \\__,_||_| |_| \\__,_|               \x1b[32m\\_| \\_| \\___||___/ \\___| \\__,_| \\___|\x1b[0m     │");
    sleep(10);
    SetCursorPosition(0,7);
    printf("│                                                            \x1b[31m_     _\x1b[0m                                     │");
    sleep(10);
    SetCursorPosition(0,8);
    printf("│                                                           \x1b[31m| |   (_)\x1b[0m                                    │");
    sleep(10);
    SetCursorPosition(0,9);
    printf("│                       \x1b[31m___    _ __     ___   _ __    __ _  | |_   _    ___    _ __\x1b[0m                      │");
    sleep(10);
    SetCursorPosition(0,10);
    printf("│                      \x1b[31m/ _ \\  | '_ \\   / _ \\ | '__|  / _` | | __| | |  / _ \\  | '_ \\\x1b[0m                     │");
    sleep(10);
    SetCursorPosition(0,11);
    printf("│                     \x1b[31m| (_) | | |_) | |  __/ | |    | (_| | | |_  | | | (_) | | | | |\x1b[0m                    │");
    sleep(10);
    SetCursorPosition(0,12);
    printf("│                      \x1b[31m\\___/  | .__/   \\___| |_|     \\__,_|  \\__| |_|  \\___/  |_| |_|\x1b[0m                    │");
    sleep(10);
    SetCursorPosition(0,13);
    printf("│                             \x1b[31m| |\x1b[0m                                                                        │");
    sleep(10);
    SetCursorPosition(0,14);
    printf("│                             \x1b[31m|_|\x1b[0m                                                                        │");
    sleep(10);
    SetCursorPosition(0,15);
    printf("│                                      ┌─────────────────────────────┐                                   │");
    sleep(10);
    SetCursorPosition(0,16);
    printf("│                                      │                             │                                   │");
    sleep(10);
    SetCursorPosition(0,17);
    printf("│                                      │       1. 게임 시작          │                                   │");
    sleep(10);
    SetCursorPosition(0,18);
    printf("│                                      │                             │                                   │");
    sleep(10);
    SetCursorPosition(0,19);
    printf("│                                      │       2. 게임 설명          │                                   │");
    sleep(10);
    SetCursorPosition(0,20);
    printf("│                                      │                             │                                   │");
    sleep(10);
    SetCursorPosition(0,21);
    printf("│                                      │       3. 게임 종료          │                                   │");
    sleep(10);
    SetCursorPosition(0,22);
    printf("│                                      │                             │                                   │");
    sleep(10);
    SetCursorPosition(0,23);
    printf("│                                      └─────────────────────────────┘                                   │");
    sleep(10);
    SetCursorPosition(0,24);
    printf("│                                                                                                        │");
    sleep(10);
    SetCursorPosition(0,25);
    printf("└────────────────────────────────────────────────────────────────────────────────────────────────────────┘");
    sleep(10);
    
}

void title_1(void)
{
    SetCursorPosition(0,0);
    printf("┌────────────────────────────────────────────────┐");
    SetCursorPosition(0,1);
    printf("│                                                │");
    SetCursorPosition(0,2);
    printf("│                                                │");
    SetCursorPosition(0,3);
    printf("│                                                │");
    SetCursorPosition(0,4);
    printf("│                                                │");
    SetCursorPosition(0,5);
    printf("│            바나나를 모아 괴물을 피해           │");
    SetCursorPosition(0,6);
    printf("│                                                │");
    SetCursorPosition(0,7);
    printf("│           다음 스테이지로 넘어 가거라          │");
    SetCursorPosition(0,8);
    printf("│                                                │");
    SetCursorPosition(0,9);
    printf("│                                                │");
    SetCursorPosition(0,10);
    printf("│                                                │");
    SetCursorPosition(0,11);
    printf("│                                                │");
    SetCursorPosition(0,12);
    printf("│         ┌─────────────────────────────┐        │");
    SetCursorPosition(0,13);
    printf("│         │   메뉴로 돌아가시겠습니까?  │        │");
    SetCursorPosition(0,14);
    printf("│         │                             │        │");
    SetCursorPosition(0,15);
    printf("│         │   1. 예         2. 아니요   │        │");
    SetCursorPosition(0,16);
    printf("│         │                             │        │");
    SetCursorPosition(0,17);
    printf("│         └─────────────────────────────┘        │");
    SetCursorPosition(0,18);
    printf("│                                                │");
    SetCursorPosition(0,19);
    printf("│                                                │");
    SetCursorPosition(0,20);
    printf("└────────────────────────────────────────────────┘");
}

void title_2(void)
{
    SetCursorPosition(0,0);
    printf("┌────────────────────────────────────────────────┐");
    SetCursorPosition(0,1);
    printf("│                                                │");
    SetCursorPosition(0,2);
    printf("│                                                │");
    SetCursorPosition(0,3);
    printf("│                                                │");
    SetCursorPosition(0,4);
    printf("│        진심으로 게임을 나가시겠습니까??        │");
    SetCursorPosition(0,5);
    printf("│                                                │");
    SetCursorPosition(0,6);
    printf("│     어차피 바쁘지도 않은데 좀더 하고 가시죠    │");
    SetCursorPosition(0,7);
    printf("│                                                │");
    SetCursorPosition(0,8);
    printf("│            다시 한번 더 묻겠습니다             │");
    SetCursorPosition(0,9);
    printf("│                                                │");
    SetCursorPosition(0,10);
    printf("│        진심으로 게임을 끄시겠습니까?           │");
    SetCursorPosition(0,11);
    printf("│                                                │");
    SetCursorPosition(0,12);
    printf("│         ┌─────────────────────────────┐        │");
    SetCursorPosition(0,13);
    printf("│         │   메뉴로 돌아가시겠습니까?  │        │");
    SetCursorPosition(0,14);
    printf("│         │                             │        │");
    SetCursorPosition(0,15);
    printf("│         │   1. 예         2. 아니요   │        │");
    SetCursorPosition(0,16);
    printf("│         │                             │        │");
    SetCursorPosition(0,17);
    printf("│         └─────────────────────────────┘        │");
    SetCursorPosition(0,18);
    printf("│                                                │");
    SetCursorPosition(0,19);
    printf("│                                                │");
    SetCursorPosition(0,20);
    printf("└────────────────────────────────────────────────┘");
}

void gametitle(void)
{
    SetCursorPosition(0,0);
    printf("┌────────────────────────────────────────────────┐");
    SetCursorPosition(0,1);
    printf("│                                                │");
    SetCursorPosition(0,2);
    printf("│                                                │");
    SetCursorPosition(0,3);
    printf("│                                                │");
    SetCursorPosition(0,4);
    printf("│                                                │");
    SetCursorPosition(0,5);
    printf("│             잠깐 게임을 시작하기 전에          │");
    SetCursorPosition(0,6);
    printf("│                                                │");
    SetCursorPosition(0,7);
    printf("│      게임 플레이 방법에 대해 알려주도록 하지   │");
    SetCursorPosition(0,8);
    printf("│                                                │");
    SetCursorPosition(0,9);
    printf("│                들을 것인가 자네?               │");
    SetCursorPosition(0,10);
    printf("│                                                │");
    SetCursorPosition(0,11);
    printf("│                                                │");
    SetCursorPosition(0,12);
    printf("│         ┌─────────────────────────────┐        │");
    SetCursorPosition(0,13);
    printf("│         │         듣겠습니까?         │        │");
    SetCursorPosition(0,14);
    printf("│         │                             │        │");
    SetCursorPosition(0,15);
    printf("│         │   1. 예         2. 아니요   │        │");
    SetCursorPosition(0,16);
    printf("│         │                             │        │");
    SetCursorPosition(0,17);
    printf("│         └─────────────────────────────┘        │");
    SetCursorPosition(0,18);
    printf("│                                                │");
    SetCursorPosition(0,19);
    printf("│                                                │");
    SetCursorPosition(0,20);
    printf("└────────────────────────────────────────────────┘");
}

